(()=>{
const K='hml_amap_key_v2',S='hml_amap_security_v2',SS='hml_field_samples_v2';
const defs={D01B:'变质岩系地层单位',D01D:'沉积/火山沉积地层单位',D02H:'火山岩岩性',D03D:'非正式地层单位',D04N:'侵入岩年代单位',D04P:'侵入岩谱系单位',D05M:'脉岩',D06S:'围岩蚀变带',D07B:'变质相带',D07H:'混合岩化带',D01J:'地质界线',D03J:'非正式地层界线',D04J:'侵入岩界线',D08D:'断层',D11K:'矿产地',D12C:'产状符号',D13B:'其它/附加面图元',D13P:'剖面线',L01J:'图幅基本信息/图框',sample_point:'黄麦岭采样剖面'};
let map,normal,sat,road,iw,ras={},rop=.72,adding=false,pending=null,myMarks=[];
const data=window.HML_LOCAL_DATA||{features:[]};
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const status=(m,t=2800)=>{let e=document.getElementById('status');e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',t)};
const open=id=>document.getElementById(id).style.display='flex',close=id=>document.getElementById(id).style.display='none';
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>close(x.dataset.close));
function title(f){let p=f.properties||{},c=p.layer_code;return p.name||p.DSN||p.QDHN||p.JJDAJ||p.GZEAB||p.CHAMAA||p.DSO||p.QDHAH||p.YSEAGE||defs[c]||c||'地质对象'}
function creds(){return{key:localStorage.getItem(K)||'',sec:localStorage.getItem(S)||''}}
function ask(){let c=creds();document.getElementById('amapKey').value=c.key;document.getElementById('securityCode').value=c.sec;if(!c.key||!c.sec){open('setupModal');return false}return true}
document.getElementById('btnSetup').onclick=()=>{let c=creds();document.getElementById('amapKey').value=c.key;document.getElementById('securityCode').value=c.sec;open('setupModal')};
document.getElementById('btnSaveSetup').onclick=()=>{let k=document.getElementById('amapKey').value.trim(),s=document.getElementById('securityCode').value.trim();if(!k||!s)return status('Key 和 securityJsCode 都要填写');localStorage.setItem(K,k);localStorage.setItem(S,s);location.reload()};
function load(){if(!ask())return;let c=creds();window._AMapSecurityConfig={securityJsCode:c.sec};let x=document.createElement('script');x.src=`https://webapi.amap.com/maps?v=2.0&key=${encodeURIComponent(c.key)}&plugin=AMap.Scale,AMap.Geolocation`;x.onload=init;x.onerror=()=>status('高德 API 加载失败，请检查 Key / securityJsCode',6000);document.head.appendChild(x)}
function init(){normal=new AMap.TileLayer();sat=new AMap.TileLayer.Satellite();road=new AMap.TileLayer.RoadNet();map=new AMap.Map('map',{center:[114.124917,31.469778],zoom:12,layers:[normal],resizeEnable:true});map.addControl(new AMap.Scale({position:'RB'}));iw=new AMap.InfoWindow({offset:new AMap.Pixel(0,-12)});initRaster();buildLegend();buildLayerSummary();addMainSample();loadSamples();bind();map.on('click',clickMap);status('黄麦岭 GitHub Pages 手机版已加载')}
function initRaster(){for(const[id,d]of Object.entries(window.HML_RASTER_LAYERS||{})){let b=d.bounds,l=new AMap.ImageLayer({url:d.url,bounds:new AMap.Bounds([b[0],b[1]],[b[2],b[3]]),opacity:rop,visible:true,zIndex:5,zooms:[3,20]});ras[id]=l;map.add(l)}}
function restore(){Object.values(ras).forEach(l=>{try{map.add(l)}catch{}})}
function buildLegend(){let h=document.getElementById('legend');h.innerHTML=`<div class="native-legend-card"><div class="native-legend-title">H-50-01 大悟幅 · 原版图例</div><img class="native-legend-thumb" id="lg1" src="data/legend/H5001_legend.webp"><div class="native-legend-actions"><button id="lg1b">放大查看</button></div></div><div class="native-legend-card"><div class="native-legend-title">H-50-07 黄陂幅 · 原版图例</div><img class="native-legend-thumb" id="lg7" src="data/legend/H5007_legend.webp"><div class="native-legend-actions"><button id="lg7b">放大查看</button></div></div>`;let o=(src,t)=>{document.getElementById('legendModalImg').src=src;document.getElementById('legendModalTitle').textContent=t;open('legendModal')};document.getElementById('lg1').onclick=document.getElementById('lg1b').onclick=()=>o('data/legend/H5001_legend.webp','H-50-01 大悟幅原版图例');document.getElementById('lg7').onclick=document.getElementById('lg7b').onclick=()=>o('data/legend/H5007_legend.webp','H-50-07 黄陂幅原版图例')}
function buildLayerSummary(){let counts={};data.features.forEach(f=>{let c=f.properties?.layer_code||'unknown';counts[c]=(counts[c]||0)+1});let h=document.getElementById('layerSwitches');h.innerHTML='<div class="native-hit-note">手机版以原版栅格显示地质图，下面列出15 km范围查询索引；搜索结果定位到对应地质对象代表位置。</div>'+Object.entries(counts).sort().map(([c,n])=>`<div class="layer-row"><span></span><span><span class="layer-code-chip">${esc(c)}</span>${esc(defs[c]||c)}</span><span class="count">${n}</span></div>`).join('')}
function addMainSample(){let f=data.features.find(f=>f.properties?.layer_code==='sample_point');if(!f)return;let p=f.geometry.coordinates,m=new AMap.Marker({position:p,content:'<div class="sample-symbol"></div>',offset:new AMap.Pixel(-11,-11),zIndex:100});m.on('click',()=>showFeature(f));map.add(m)}
function activate(n){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===n));document.querySelectorAll('.tabbody').forEach(x=>x.classList.toggle('active',x.id===`tab-${n}`))}
function showFeature(f){let p=f.properties||{},rows=Object.entries(p).filter(([,v])=>v!==null&&v!==''&&String(v)!=='nan');let c=p.layer_code||'',xy=f.geometry.coordinates;document.getElementById('featureInfo').innerHTML=`<div class="feature-title">${esc(title(f))}</div><div class="hint">${esc(p.source_sheet||'')} · ${esc(c)} · ${esc(defs[c]||'')}</div><table class="attr-table">${rows.map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table><button class="primary wide" id="navNow">高德导航</button>`;document.getElementById('navNow').onclick=()=>nav(xy[0],xy[1],title(f));activate('info');map.setZoomAndCenter(15,xy);iw.setContent(`<b>${esc(title(f))}</b><br><small>${esc(defs[c]||c)}</small>`);iw.open(map,xy)}
function nav(x,y,n){window.open(`https://uri.amap.com/navigation?to=${x},${y},${encodeURIComponent(n||'目标点')}&mode=car&policy=1&src=HMLFieldMap&callnative=1`,'_blank')}
function search(){let q=document.getElementById('searchInput').value.trim().toLowerCase(),h=document.getElementById('searchResults');if(!q)return h.innerHTML='';let hits=data.features.filter(f=>(title(f)+' '+Object.values(f.properties||{}).join(' ')).toLowerCase().includes(q)).slice(0,100);h.innerHTML=`<div class="hint">找到 ${hits.length} 个结果</div>`+hits.map((f,i)=>`<div class="result" data-i="${i}"><b>${esc(title(f))}</b><small>${esc(f.properties?.source_sheet||'')} · ${esc(f.properties?.layer_code||'')}</small></div>`).join('');h.querySelectorAll('.result').forEach((e,i)=>e.onclick=()=>showFeature(hits[i]))}
function samples(){try{return JSON.parse(localStorage.getItem(SS)||'[]')}catch{return[]}}function save(a){localStorage.setItem(SS,JSON.stringify(a))}
function next(){let n=1;samples().forEach(s=>{let m=String(s.code||'').match(/HML-(\d+)/);if(m)n=Math.max(n,+m[1]+1)});return`HML-${String(n).padStart(3,'0')}`}
function clickMap(e){if(!adding)return;pending=[e.lnglat.lng,e.lnglat.lat];document.getElementById('sampleCoord').textContent=`GCJ-02：${pending[0].toFixed(6)}, ${pending[1].toFixed(6)}`;document.getElementById('sampleCode').value=next();['sampleLithology','sampleAttitude','sampleDistance','sampleRelation','sampleNote'].forEach(id=>document.getElementById(id).value='');adding=false;document.getElementById('btnAddSample').classList.remove('primary');open('sampleModal')}
function loadSamples(){myMarks.forEach(m=>map.remove(m));myMarks=[];samples().forEach(s=>{let m=new AMap.Marker({position:[s.lng,s.lat],label:{content:s.code,direction:'right'},zIndex:110});m.on('click',()=>{map.setZoomAndCenter(16,[s.lng,s.lat]);document.getElementById('featureInfo').innerHTML=`<div class="feature-title">${esc(s.code)}</div><table class="summary-table"><tr><td>岩性</td><td>${esc(s.lithology)}</td></tr><tr><td>产状</td><td>${esc(s.attitude)}</td></tr><tr><td>距脉体/反应带</td><td>${esc(s.distance)}</td></tr><tr><td>流体/构造</td><td>${esc(s.relation)}</td></tr><tr><td>备注</td><td>${esc(s.note)}</td></tr></table><button class="primary wide" id="navS">高德导航</button>`;document.getElementById('navS').onclick=()=>nav(s.lng,s.lat,s.code);activate('info')});map.add(m);myMarks.push(m)});document.getElementById('sampleList').innerHTML=samples().map(s=>`<div class="sample-card"><b>${esc(s.code)}</b><br><small>${esc(s.lithology||'')} · ${s.lng.toFixed(6)}, ${s.lat.toFixed(6)}</small></div>`).join('')||'<div class="hint">尚未记录自采点。</div>'}
function dl(n,t,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(){let q=id=>document.getElementById(id);q('btnMenu').onclick=()=>q('panel').classList.toggle('open');q('btnClosePanel').onclick=()=>q('panel').classList.remove('open');document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>activate(x.dataset.tab));q('rasterH5001').onchange=e=>e.target.checked?ras.H5001.show():ras.H5001.hide();q('rasterH5007').onchange=e=>e.target.checked?ras.H5007.show():ras.H5007.hide();q('focusH5001').onclick=()=>{let b=window.HML_RASTER_LAYERS.H5001.bounds;map.setBounds(new AMap.Bounds([b[0],b[1]],[b[2],b[3]]))};q('focusH5007').onclick=()=>{let b=window.HML_RASTER_LAYERS.H5007.bounds;map.setBounds(new AMap.Bounds([b[0],b[1]],[b[2],b[3]]))};q('rasterOpacitySlider').oninput=e=>{rop=+e.target.value;q('rasterOpacityValue').textContent=Math.round(rop*100)+'%';Object.values(ras).forEach(l=>l.setOpacity(rop))};q('btnSearch').onclick=search;q('searchInput').onkeydown=e=>{if(e.key==='Enter')search()};q('btnBase').onclick=()=>{if(q('btnBase').dataset.sat==='1'){map.setLayers([normal]);q('btnBase').dataset.sat='0';q('btnBase').textContent='卫星图'}else{map.setLayers([sat,road]);q('btnBase').dataset.sat='1';q('btnBase').textContent='普通图'}restore()};q('btnLocate').onclick=()=>AMap.plugin('AMap.Geolocation',()=>new AMap.Geolocation({enableHighAccuracy:true,timeout:12000,zoomToAccuracy:true}).getCurrentPosition((st,r)=>st==='complete'?(map.setZoomAndCenter(15,r.position),status(`定位成功${r.accuracy?`，精度约${Math.round(r.accuracy)} m`:''}`)):status('定位失败：请允许浏览器定位权限',4500)));q('btnAddSample').onclick=()=>{adding=!adding;q('btnAddSample').classList.toggle('primary',adding);status(adding?'请在地图上点击采样位置':'已取消新增样点')};q('btnSaveSample').onclick=()=>{if(!pending)return;let s={code:q('sampleCode').value.trim()||next(),lng:pending[0],lat:pending[1],lithology:q('sampleLithology').value.trim(),attitude:q('sampleAttitude').value.trim(),distance:q('sampleDistance').value.trim(),relation:q('sampleRelation').value.trim(),note:q('sampleNote').value.trim(),time:new Date().toISOString()},a=samples();a.push(s);save(a);close('sampleModal');loadSamples();status('样点已保存')};q('btnExportCSV').onclick=()=>{let a=samples(),heads=['code','lng_gcj02','lat_gcj02','lithology','attitude','distance','relation','note','time'],qq=v=>'"'+String(v??'').replace(/"/g,'""')+'"';dl('Huangmailing_samples.csv','\ufeff'+heads.join(',')+'\n'+a.map(s=>heads.map(h=>qq(h==='lng_gcj02'?s.lng:h==='lat_gcj02'?s.lat:s[h])).join(',')).join('\n'),'text/csv')};q('btnExportGeoJSON').onclick=()=>dl('Huangmailing_samples_GCJ02.geojson',JSON.stringify({type:'FeatureCollection',features:samples().map(s=>({type:'Feature',geometry:{type:'Point',coordinates:[s.lng,s.lat]},properties:s}))},null,2),'application/geo+json');q('btnClearSamples').onclick=()=>{if(confirm('确定清空本浏览器保存的全部自采点？')){save([]);loadSamples()}}}
load();
})();